# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nvdeb101',
                'doc_host': 'https://mckjzhangxk.github.io',
                'git_url': 'https://github.com/mckjzhangxk/nvdeb101',
                'lib_path': 'nvdeb101'},
  'syms': { 'nvdeb101.card': { 'nvdeb101.card.Card': ('card.html#card', 'nvdeb101/card.py'),
                               'nvdeb101.card.Card.__eq__': ('card.html#card.__eq__', 'nvdeb101/card.py'),
                               'nvdeb101.card.Card.__init__': ('card.html#card.__init__', 'nvdeb101/card.py'),
                               'nvdeb101.card.Card.__repr__': ('card.html#card.__repr__', 'nvdeb101/card.py')},
            'nvdeb101.deck': { 'nvdeb101.deck.Deck': ('deck.html#deck', 'nvdeb101/deck.py'),
                               'nvdeb101.deck.Deck.__contains__': ('deck.html#deck.__contains__', 'nvdeb101/deck.py'),
                               'nvdeb101.deck.Deck.__init__': ('deck.html#deck.__init__', 'nvdeb101/deck.py'),
                               'nvdeb101.deck.Deck.__len__': ('deck.html#deck.__len__', 'nvdeb101/deck.py'),
                               'nvdeb101.deck.Deck.__repr__': ('deck.html#deck.__repr__', 'nvdeb101/deck.py'),
                               'nvdeb101.deck.Deck.pop': ('deck.html#deck.pop', 'nvdeb101/deck.py')}}}
