# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['ranks', 'suits', 'Card']

# %% ../nbs/00_card.ipynb 3
ranks=[None,'A','3','4','5','6','7','8','9','J','Q','K']
suits=['♠','♣','♥','♦']

# %% ../nbs/00_card.ipynb 6
class Card(): 
    "扑克牌的定义"
    def __init__(self,
                 suit:int, #表示扑克牌花色
                 rank:int  #扑克上的数字
                ):
        self.suit,self.rank=suit,rank
    def __repr__(self):
        return f"{ranks[self.rank]}{suits[self.suit]}"
    def __eq__(self,o:'Card'):
        return self.suit==o.suit and self.rank==o.rank
    __str__=__repr__
