# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 3
from .card import *
from fastcore.utils import *

# %% ../nbs/01_deck.ipynb 5
class Deck(): 
    "扑克牌的的定义的定义"
    def __init__(self):
        self.deck=[Card(i,j) for i in range(4) for j in range(12)]
    def __repr__(self):
        return f"{self.deck}"
    def __len__(self):
        "扑克牌的数量"
        return len(self.deck)
    def __contains__(self,c):
        return c in self.deck
    __str__=__repr__

# %% ../nbs/01_deck.ipynb 10
@patch
def pop(self:Deck,
       index:int=-1 #取牌的位置
    ):
    "取出最后一张牌"
    return self.deck.pop()
